version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: galileosky-db
    environment:
      POSTGRES_DB: galileosky
      POSTGRES_USER: galileosky
      POSTGRES_PASSWORD: qxURBpBlpCAZ7qk-
    ports:
      - "5432:5432"  
    volumes:
      - galileosky_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galileosky -d galileosky"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    command: -c work_mem=64MB -c max_wal_size=2GB

  migrate-db:
    image: python:3.12-slim
    container_name: migrate-db
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: galileosky
      POSTGRES_USER: galileosky
      POSTGRES_PASSWORD: qxURBpBlpCAZ7qk-
      POSTGRES_PORT: 5432
    volumes:
      - ./app/migrations:/app/migrations
      - ./app/scripts:/app/scripts
    working_dir: /app
    command: 
      - sh
      - -c 
      - |
        pip install psycopg2-binary &&
        python /app/scripts/migrate.py
    restart: on-failure
    
  app:
    build: ./app
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_healthy
      migrate-db:
        condition: service_started
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: galileosky
      POSTGRES_USER: galileosky
      POSTGRES_PASSWORD: qxURBpBlpCAZ7qk-
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
     
volumes:
  galileosky_data: 
